### ISSUE TITLE
deprecated /deep/

### ISSUE THREAD

**Issue by nueko** [EladBezalel/material2-start#28]
I think we should remove the shadow-piercing for clarify
https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by EladBezalel** [comment]
sgtm

**Comment by nueko** [comment]
what about this?
```css
/**
* styles.css
**/
...
mat-list-item mat-icon > svg {
  border-radius: 50%
}

```
```css
/**
* app.component.css
**/

:host {
  display: flex;
  flex: 1;
}

mat-sidenav {
  width: 320px;
}

.content {
  padding: 12px;
}
/* removed
/deep/ mat-icon.avatar
*/
mat-list-item mat-icon {
  overflow: hidden;
  width: 64px;
  height: 64px;
/*  border-radius: 50%; */
  margin: 12px;
}

.fab-bottom-right {
  position: fixed;
 /*add z-index*/
  z-index: 10;
  right: 16px;
  bottom: 16px;
}

/* we don't need this as it makes the sidenav not fill the height by 100% and looks like floating
/deep/ .mat-list-item-content {
  height: auto !important;
}
 */
```
